version: "2.1"

services:
  update-manager:
    build: .
    restart: unless-stopped
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    labels:
      io.balena.features.supervisor-api: "1"