#!/bin/sh
set -eu

echo "Arrancando update-manager..."

echo "DEV_ROS_DOMAIN_ID: ${DEV_ROS_DOMAIN_ID:-9}"
echo "DEV_CYCLONEDDS_NETWORK_INTERFACE: ${DEV_CYCLONEDDS_NETWORK_INTERFACE:-eth0}"

export ROS_DOMAIN_ID="${DEV_ROS_DOMAIN_ID:-9}"
export CYCLONEDDS_NETWORK_INTERFACE="${DEV_CYCLONEDDS_NETWORK_INTERFACE:-eth0}"

echo "ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}"
echo "CYCLONEDDS_NETWORK_INTERFACE: ${CYCLONEDDS_NETWORK_INTERFACE}"

exec python3 -u /app/main.py